# Generated by Django 4.2.9 on 2024-02-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MPAARating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('imgPath', models.TextField()),
                ('duration', models.PositiveBigIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('userRating', models.CharField(max_length=5)),
                ('genre', models.ManyToManyField(to='movie.genre')),
                ('mpaaRating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie.mpaarating')),
            ],
        ),
    ]
