# Generated by Django 4.2.9 on 2024-02-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_mpaarating_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imgPath',
            field=models.ImageField(upload_to='assets/images/'),
        ),
    ]
