# Generated by Django 4.2.9 on 2024-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movies_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imgPath',
            field=models.ImageField(upload_to='static/assets/images/'),
        ),
    ]
